users/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #url(r'^$', views.home_page, name='home_page'),
    url(r'^sign_page/$', views.sign_page, name='sign_page'),
    url(r'^logout_page/$', views.logout_view, name='logout_view'),
    url(r'^register_page/$', views.register_page, name='register_page'),
    url(r'^activate/(?P<key>.+)$', views.activation, name='activation'),
    url(r'^new-activation-link/(?P<user_id>.+)/$',views.new_activation_link, name='new_activation_link	'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^reset_password/$', views.reset_password, name='reset_password'), 
]

mc/models.py
from __future__ import unicode_literals
from django.db import models
import re, uuid

class TheEmails(models.Model):
    emails = models.CharField(max_length=255, default="n/a")

class UserList(models.Model):
    username = models.CharField(max_length=255)
    subreddits = models.TextField()
    listuuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  
    label = models.CharField(max_length=255, null=True)

mc/forms.py
from django import forms
from django.core.validators import EmailValidator

class EmailNewPass(forms.Form):
    aemail = forms.EmailField(required=True,label="",widget=forms.EmailInput(attrs={'placeholder': 'Email','class':'form-control input-perso','id':'email_input'}),max_length=100,error_messages={'invalid': ("Email invalid")},validators=[EmailValidator])

class subs(forms.Form):
    Choices = (
            ("AskReddit,funny,explainlikeimfive,mildlyinteresting,showerthoughts,music,pics,jokes", "popular defaults"),
            ("Art","Art"),
            ("AskReddit","AskReddit"),
("askscience","askscience"),
("aww","aww"),
("books","books"),
("creepy","creepy"),
("dataisbeautiful","dataisbeautiful"),
("DIY","DIY"),
("Documentaries","Documentaries"),
("EarthPorn","EarthPorn"),
("explainlikeimfive","explainlikeimfive"),
("food","food"),
("funny","funny"),
("gaming","gaming"),
("gifs","gifs"),
("history","history"),
("jokes","jokes"),
("LifeProTips","LifeProTips"),
("movies","movies"),
("music","music"),
("pics","pics"),
("science","science"),
("ShowerThoughts","ShowerThoughts"),
("space","space"),
("sports","sports"),
("tifu","tifu"),
("todayilearned","todayilearned"),
("videos","videos"),
("worldnews","worldnews"),
            )
    subreddits = forms.ChoiceField(choices=Choices,widget=forms.Select(attrs={'class':'btn btn-primary btn-round product-btn dropdown'}))

class Usersubs(forms.Form):
    Choices = (
("AskReddit,funny,explainlikeimfive,mildlyinteresting,showerthoughts,music,pics,jokes", "popular defaults"),
("politics,the_donald,news,worldnews,sandersforpresident,Libertarian", "political"),
("sports,nba,soccer,olympics,MLS,hockey,Tennis,Golf,mlb", "sports"),
("bitcoin,technology,programming,gaming,gadgets,android,apple", "tech"),
("pics,videos,dataisbeautiful,aww,food,oldschoolcool,earth_porn,wholesomememes", "visual media"),
            )
    subreddits = forms.ChoiceField(choices=Choices,widget=forms.Select(attrs={'class':'btn btn-primary btn-round product-btn dropdown'}))

users/forms.py
from django import forms
from django.core.validators import EmailValidator, URLValidator
from django.template import Context, Template
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from users.models import Profil
import datetime
from django.utils import timezone
import re 
from django.core.exceptions import ValidationError
#from nocaptcha_recaptcha.fields import NoReCaptchaField


class RegistrationForm(forms.Form):
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'id':'username_input','placeholder': 'username','class':'form-control input-perso'}),max_length=30,min_length=3)#,validators=[isValidUsername, validators.validate_slug])
    email = forms.EmailField(required=True,label="",widget=forms.EmailInput(attrs={'placeholder': 'Email','class':'form-control input-perso','id':'email_input'}),max_length=100,error_messages={'invalid': ("Email invalid")},validators=[EmailValidator])
    password1 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'choose a password','class':'form-control input-perso', 'id':'password1'}))
    password2 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'confirm password','class':'form-control input-perso','id':'password2'}))
    #captcha = NoReCaptchaField()



    #Override of clean method for password check
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password2

    #Override of save method for saving both User and Profil objects
    def save(self, datas):
        u = User.objects.create_user(datas['username'],
                                     datas['email'],
                                     datas['password1'])
        
        u.is_active = False
        u.save()
        profil=Profil()
        profil.user=u
        profil.activation_key=datas['activation_key']
        profil.key_expires=timezone.now() + datetime.timedelta(days=1)
        
        profil.save()
        return u

    #Handling of activation email sending ------>>>!! Warning : Domain name is hardcoded below !!<<<------
    #I am using a text file to write the email (I write my email in the text file with templatetags and then populate it with the method below)
    def sendEmail(self, datas):
        link="http://trendpinger.com/activate/"+datas['activation_key']
        c=Context({'activation_link':link,'email':datas['email']})
        f = open(datas['email_path'], 'r')
        t = Template(f.read())
        f.close()
        message=t.render(c)
        #print unicode(message).encode('utf8')
        
        send_mail(datas['email_subject'], message, 'con@bl4btc.io', [datas['email']], fail_silently=False)


class SignInForm(forms.Form):
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'id':'username_input','placeholder': 'username','class':'form-control input-perso'}),max_length=30,min_length=3)#,validators=[isValidUsername, validators.validate_slug])
    password1 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'choose a password','class':'form-control input-perso', 'id':'password_input'}))
    #captcha = NoReCaptchaField()

class ChangePassForm(forms.Form):
    password1 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'choose a password','class':'form-control input-perso', 'id':'password_input1'}))
    newpassword1 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'choose a password','class':'form-control input-perso', 'id':'password_input2'}))
    newpassword2 = forms.CharField(required=True,label="",max_length=50,min_length=6,widget=forms.PasswordInput(attrs={'placeholder': 'choose a password','class':'form-control input-perso', 'id':'password_input3'}))
    #captcha = NoReCaptchaField()


class EmailNewPass(forms.Form):
    email = forms.EmailField(required=True,label="",widget=forms.EmailInput(attrs={'placeholder': 'Email','class':'form-control input-perso','id':'email_input'}),max_length=100,error_messages={'invalid': ("Email invalid")},validators=[EmailValidator])
    #captcha = NoReCaptchaField()

mc/views.py
from django.shortcuts import render, redirect
from sklearn.externals import joblib
from django.http import Http404, HttpResponse
import praw
import datetime
from operator import attrgetter
import sys
import numpy as np
from mc.forms import subs, EmailNewPass, Usersubs
from mc.models import UserList
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from lxml import html
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.contrib.auth import authenticate, login, logout
from rest_framework import viewsets, permissions, status, authentication
import requests
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from mc.serializers import CommentSerializer
from google.cloud import vision

reddit = praw.Reddit(client_id='r7gDiisP6rFi7g',
                     client_secret='nLEQAhbP34dCQNBNzy_brxE_zGI',
                     user_agent='pythonscript:com.example.frontandrisingchecker:v0.1 (by /u/redditpirateroberts)',
                     username='redditpirateroberts',
                     password='aDreamer24')

class Post:
        def __init__(self, subreddit, author, title, score, numOfComments, permalink, diff_minutes):
                self.subreddit = subreddit
                self.author = author
                self.title = title
                self.score = score
                self.numOfComments = numOfComments
                self.permalink = permalink
                self.diff_minutes = diff_minutes

class PostAPI:
        def __init__(self, subreddit, author, title, score, numOfComments, permalink, diff_minutes, url, domain, selftext):
                self.subreddit = subreddit
                self.author = author
                self.title = title
                self.score = score
                self.numOfComments = numOfComments
                self.permalink = permalink
                self.diff_minutes = diff_minutes
                self.url = url
                self.domain = domain
                self.selftext = selftext

class HotPost:
        def __init__(self, subreddit, title, permalink, rating):
                self.subreddit = subreddit
                self.title = title
                self.permalink = permalink
                self.rating = rating

class BestPost:
        def __init__(self, subreddit, author, title, score, numOfComments, permalink, diff_minutes, chance_to_go_viral):
                self.subreddit = subreddit
                self.author = author
                self.title = title
                self.score = score
                self.numOfComments = numOfComments
                self.permalink = permalink
                self.diff_minutes = diff_minutes
                self.chance_to_go_viral = chance_to_go_viral



rfc = joblib.load('/home/connlloc/sites/mc/modelSvm.pkl')
trendingPosts = []

def apiDocs(request):
    return render(request,'apiDocs.html')

class Misc:
    

    def auth(self, authtoken):
        
        user = User.objects.get(auth_token=authtoken)
        if user.is_authenticated():
            return user
        elif user.exists() == False:
            return HttpResponse('user does not exist', status=status.HTTP_400_BAD_REQUEST)
        elif user.is_authenticated() == False:
            return HttpResponse('you must log in first', status=status.HTTP_400_BAD_REQUEST)
        else:
            return HttpResponse('user does not exist or authtoken is incorrect', status=status.HTTP_400_BAD_REQUEST)

class redditSearch(APIView):


    def post(self, request, *args):
        auth = Misc()
        auth.auth(request.data['authtoken'])
        posts = returnTrending("politics",[])
        l = []
        for post in posts:
            entry = {
            "subreddit": post.subreddit,
        "title": post.subreddit,
        "permalink":  post.permalink,
        "rating": post.rating, 
        }
            l.append(entry)
        serializer = CommentSerializer(data=l, many=True)
        
        if serializer.is_valid(): 
            return Response(serializer.data, status=status.HTTP_200_OK)
        return HttpResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


##----Mark's additions:
class GetHottestPosts(APIView):


    def get(self, request, *args):
#       final arguments for this function:
#            args[0] - minimum_chance_to_go_viral - float - 0.91 - default: 0.0
#            args[1] - content_type - string_list - gifs,pics,videos,text,link - default: all
#            args[2] - platforms - string_list - reddit,twitter,youtube - default: all
#            args[3] - content_tags - string_list - cat,mammal,politics - default: none
#            args[4] - platform_specific_searches - string_list - reddit:politics,news,worldnews;twitter:got - default: none
#            args[5] - number_of_post_to_return - int - 10 - default: 20

#       current arguments for this function:
#            args[0] - minimum_chance_to_go_viral - float - 0.91 - default: 0.0
#            args[1] - content_type - string_list - gif,img,video,text,link - default: all
#            args[2] - specific_content_tags - string_list - cat,mammal,politics - default: none
#            args[3] - specific_subreddits - string_list - reddit:politics,news,worldnews; - default: none
#            args[4] - number_of_post_to_return - int - 10 - default: 20

        auth = Misc()
        auth.auth(args[0])
        number_of_posts_to_return = args[5]
        number_of_posts_to_return = int(number_of_posts_to_return)
        empty_list = []
        posts = returnTrendingAPI(args[1], args[2], args[3], args[4], number_of_posts_to_return, empty_list)
        l = []
        mylist = []     
        for post in posts:
            #add platform for entry 
            
                   
            entry = {
            "subreddit": post.subreddit,
            "title": post.title,
            "permalink":  post.permalink,
            "rating": post.rating, 
            }  
            l.append(entry)
        serializer = CommentSerializer(data=l, many=True)
        posts = []       
        if serializer.is_valid(): 
            return Response(serializer.data, status=status.HTTP_200_OK)
        return HttpResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


##----End of Mark's additions.

def get_hottest_subs():
        page = requests.get('http://redditlist.com/')
        tree = html.fromstring(page.content)
        hot_subs = []
        for i in range (0, 6):
                hot_sub = tree.xpath('//*[@id="listing-parent"]/div[1]/div[' + str(i+2) + ']/span[3]/a/text()')
                hot_subs.append(hot_sub)

        for subreddit in hot_subs:
                fillers = []
                for submission in reddit.subreddit(subreddit[0]).new(limit=50):
                    author = submission.author

                    title = submission.title
                    score = submission.score
                    numOfComments = submission.num_comments
                    permalink = submission.permalink
                    timeCreated = submission.created_utc

                    timeOfPost = datetime.datetime.utcfromtimestamp(timeCreated)
                    timeNow = datetime.datetime.utcnow()

                    diff = timeNow - timeOfPost
                    diff_minutes = (diff.days * 24 * 60) + (diff.seconds/60)

                    if diff_minutes == 0:
                        diff_minutes = 1
                    if diff_minutes < 140:
                        prediction = rfc.predict_proba([[score,numOfComments,diff_minutes,0]])

                        if prediction[0][1] > 0.60:
                            chance_to_go_viral = prediction[0][1]
                            chance_to_go_viral=chance_to_go_viral * 100
                            chance_to_go_viral = round(chance_to_go_viral, 2)
                            return BestPost(subreddit, author, title, score, numOfComments, permalink, diff_minutes, chance_to_go_viral)


def email(request):
    if request.method == 'POST':       
        form = EmailNewPass(request.POST)
        if form.is_valid():
            email = form.cleaned_data['aemail']
            e = TheEmails(emails=email)
            e.save()
            emailSaved = True
            form = subs()
            return render(request, 'home.html',{'form':form, 'emailSaved':emailSaved})
    else:
        form = subs()
        emailSaved = False
        return render(request, 'home.html',{'form':form, 'emailSaved':emailSaved})

@never_cache
@login_required(login_url='/sign_page/')
def userView(request):
    
    try:
        customlist = UserList.objects.filter(username=request.user.username)
        
    except:
        customlist = None

    
    trendingPosts = []
    if request.method == 'POST':
        form = subs(request.POST)
        if form.is_valid():
            subreddit = form.cleaned_data['subreddits']

            subreddits = subreddit.split(',')
            if len(subreddits) > 1:
                for subreddit in subreddits:
                    TrendingPosts = returnTrending(subreddit, trendingPosts)

            else:
                trendingPosts = returnTrending(subreddit, trendingPosts)

            for post in trendingPosts:
                post.rating=post.rating * 100 
                post.rating = round(post.rating, 2)
        form = Usersubs()
        return render(request,'user.html', {'Posts':trendingPosts,'form':form,'customlist':customlist})
    form = Usersubs()

    return render(request,'user.html', {'Posts':trendingPosts,'form':form,'customlist':customlist})


@never_cache
@login_required(login_url='/sign_page/')
def deleteList(request, listuuid):
    l = UserList.objects.get(listuuid=listuuid)
    if request.user.username == l.username:
        l.delete()

mc/templates/apiDocs.html
api docs coming soon

mc/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="google-site-verification" content="QcG5yrdmqea3w8M8rDrMNDGlhAcJ4x-rDuXR2WGlnJM" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/static/css/jquery-ui.css">
    <link href="/static/css/custom.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <link href="/static/fonts/fontawesome-webfont.ttf" rel="stylesheet" media="screen">
    <script id="infogram_0_reddit_posts-7434" title="Reddit Posts" src="//e.infogr.am/js/dist/embed.js?Nt7" type="text/javascript"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  
                
      
      
      {% block content %}            
      {% endblock %}
     
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1856281142889780",
    enable_page_level_ads: true
  });
</script>         
<script>
 
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-101028073-1', 'auto');
  ga('send', 'pageview');


</script>

</html>

mc/templates/landing.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-101028073-1', 'auto');
  ga('send', 'pageview');

</script>
<div class="contentBorder1">
<form class="form-inline" action="/email/" method="post" enctype="multipart/form-data">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="tradewrapper">
    <label class="tradelabel">Sign up for email updates</label>
        {{ form.aemail.errors }}

        {{ form.aemail }}
    
    </div>
<button type="submit" id="sign-up" class="btn btn-success btn-lg">
<i class="fa fa fa-envelope"></i>&nbsp;Sign up</button>
{% if Posts %}
	<table class="table">
 		<tr>
		    <th>Subreddit</th>
		    <th>Title/Link</th> 
		    <th>% chance of making /r/all</th> 
  		</tr>
{% for post in Posts %}
  		<tr>
                    
		    <td>{{post.subreddit}}</td>
		    <td><a href={{post.permalink}}>{{post.title}}</a></td> 
		    <td>{{post.rating}}</td>
  		</tr>
{% endfor %}
	</table>
{%endif%}
</div>


{% endblock %}

mc/templates/user.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<title>reddit post prediction</title>
<body class="background">
<div class="login">


 
</div>
<div class="contentBorder">
  <ul class="nav nav-tabs" id="pills">

    <li class="active"><a data-toggle="tab" href="#home">search for viral posts</a></li>
    


    <p class="generictext1">welcome back, {{ request.user.username }}</p>
     <a href="{% url 'logout_view' %}" id="signIn"><i class="fa fa-sign-out" aria-hidden="true"></i>
    Log out</a>
  </ul>

  <div class="tab-content"> 
    <div id="home" class="tab-pane fade in active">
     
           <a href="{% url 'user-view' %}"><img class="logoimg" src="http://res.cloudinary.com/anonshot/image/upload/trendpingerwhite_sqbo66.png"></a>
        
    <p class="generictext">search reddit for upcoming viral posts with machine learning</p>
   <div id="loading" class="sk-cube-grid">
    <div class="sk-cube sk-cube1"></div>
    <div class="sk-cube sk-cube2"></div>
    <div class="sk-cube sk-cube3"></div>
    <div class="sk-cube sk-cube4"></div>
    <div class="sk-cube sk-cube5"></div>
    <div class="sk-cube sk-cube6"></div>
    <div class="sk-cube sk-cube7"></div>
    <div class="sk-cube sk-cube8"></div>
    <div class="sk-cube sk-cube9"></div>
   </div>
   <div id="mywrapper">
   
    <form class="form-inline" action="/user-view/" method="post" enctype="multipart/form-data">
  
   
    {% csrf_token %}
    <div class="tradewrapper">
    <label class="tradelabel">Choose a subreddit or group of subreddits to scan</label>
       <select class="btn btn-primary btn-round product-btn dropdown" id="id_subreddits" name="subreddits" required>
<option value="AskReddit,funny,explainlikeimfive,mildlyinteresting,showerthoughts,music,pics,jokes">popular defaults</option>
<option value="politics,the_donald,news,worldnews,sandersforpresident,Libertarian">political</option>
<option value="sports,nba,soccer,olympics,MLS,hockey,Tennis,Golf,mlb">sports</option>
<option value="bitcoin,technology,programming,gaming,gadgets,android,apple">tech</option>
<option value="pics,videos,dataisbeautiful,aww,food,oldschoolcool,earth_porn,wholesomememes">visual media</option>
</select>
    
    
    <button type="submit" id="sign-up" class="btn btn-success btn-lg">
    <i class="fa fa-check-square-o"></i>&nbsp;Ping</button>
    </div>
    </form>
   <a class="userlistlink" href="{% url 'user-list' %}"><button type="submit" id="sign-up" class="btn btn-success btn-lg"><i class="fa fa-list"></i> create or delete your custom lists</button></a>
    
   {% if Posts %}
       <div class="tablewrapper">
	<table class="table" id="mytable">
 		<tr>
		    <th><p>Subreddit</p></th>
		    <th><p>Title/Link</p></th> 
		    <th><p>% chance of making /r/all</p></th> 
  		</tr>
   {% for post in Posts %}
  		<tr>
                    
		    <td><p>{{post.subreddit}}</p></td>
		    <td><a href={{post.permalink}}>{{post.title}}</a></td> 
		    <td><p>{{post.rating}}</p></td>
  		</tr>
 
   {% endfor %}
	</table>
       </div>
    {% else %}
 <div class="spacer"></div>
   {%endif%}
  </div>
    </div>
       
  </div>
</div>


   </div>
  </div>
 </div> 
 <div class="push"></div>
</div>
<footer id="footer">site designed by <a href="http://connellgough.com">connell gough</a></footer>

</body>
<script type="text/javascript" >

{% if customlist %}
$( document ).ready(function() {
    {% for l in customlist %}
    $('#id_subreddits').append($('<option>', {
    value : "{{ l.subreddits }}",
    text : "{{ l.label }}"
    
}));
{%endfor%}
});
{% endif %}

</script>

<script type="text/javascript">
$(document).ready(function(){
    $("#loading").hide();
    $("#sign-up").click(function(){
        $("#loading").show();
        $("#sign-up").hide();
        $("#mywrapper").hide();
        $("#footer").hide();
    });
    $("#sign-up").click(function(){
        $("#welcomeText").hide();
    });
});
</script>




{% endblock %}

mc/templates/userlist.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<title>reddit post prediction</title>
<body class="background">
<div class="contentBorder">
<ul class="nav nav-tabs" id="pills">

    <li class="active"><a data-toggle="tab" href="#home">search for viral posts</a></li>
    


    <p class="generictext1">welcome back, {{ request.user.username }}</p>
     <a href="{% url 'logout_view' %}" id="signIn"><i class="fa fa-sign-out" aria-hidden="true"></i>
    Log out</a>
  </ul>

  <div class="tab-content"> 
    <div id="home" class="tab-pane fade in active">
     
           <a href="{% url 'user-view' %}"><img class="logoimg" src="http://res.cloudinary.com/anonshot/image/upload/trendpingerwhite_sqbo66.png"></a>
<h1 class="landing-header2">create your own list</h1>
    <form class="form-inline" action="/user-list/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="tradewrapper">
    <label class="tradelabel">add subreddits</label>
        <input name="subreddits" type="hidden">
        <div id="divgrid" >
         
        </div>
        </input>
       <input id="subreddits" class='form-control' placeholder="enter a subreddit" type='text'>
    
    
    <button type="button" id="addinput" class="btn btn-success btn-lg">
    <i class="fa fa-plus"></i>&nbsp;add</button>
    <input name="label" class='form-control' placeholder="list label" type='text'>
    <button type="submit" id="sign-up" class="btn btn-success btn-lg">
    <i class="fa fa-check-square-o"></i>&nbsp;save</button>
    </div>
    </form>

  </div>
   {% if customlist %}
       <div class="tablewrapper">
	<table class="table" id="mytable">
   {% for post in customlist %}
  		<tr>
		    <td><p>{{post.subreddits}}</p></td>
		    <td><p>{{post.label}}<p></td> 
		    <td><a href="{% url 'delete-list' post.listuuid %}">delete</p></td>
  		</tr>
 
   {% endfor %}
	</table>
       </div>
    {% else %}
 <div class="spacer"></div>
   {%endif%}
 </div>
</div>
</body>

<script type="text/javascript" >
var counter = 0;

$("#optionbutton1").click(function(){
    $("#footer").hide();
    counter = counter - 1;
});
$("#addinput").click(function(){
counter++;
if (counter >= 11) {
    document.getElementById('subreddits').value = 'maximum of 10 subreddits',
    document.getElementById('addinput').hide();
}

$('#divgrid').append($('<button>', {
    id : 'optionbutton' + counter,
    type : 'button',
    class: 'btn btn-basic btn-sm',
}));
var value = document.getElementById('subreddits').value
document.getElementById('optionbutton' + counter).innerHTML= '<input type="hidden" name="subreddits" value=' + value + '><option class="generictext2" value=' + value + '>' + value + ' X</option>';

document.getElementById('subreddits').value= '';
});

</script>

{% endblock %}